### ISSUE TITLE
log tags don't work

### ISSUE THREAD

**Issue by richmolj** [stve/silencer#14]
On Rails 4, setting `config.log_tags = [:uuid]` will not work with this middleware.

**Comment by stve** [comment]
@richmolj do you recall what version of the gem you were using when you tested this? It's been a while since I worked on this but there are tests for `log_tags` so I there is some support in place.

**Comment by richmolj** [comment]
I've since moved away from this gem, sorry, I am not sure :frowning:

**Comment by stve** [comment]
no worries, thanks for trying it out

**Comment by CodeMonkeySteve** [comment]
I'm also missing tags in my logs with Silencer, both v0.6.0 and v1.0.0.rc3.  I'm using Rails 4.1.15, with this configuration:
```
config.log_tags = [ :uuid ]
config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT, 0))
...
config.middleware.swap Rails::Rack::Logger, Silencer::Logger, :get => [%r{^/assets/}, %r{^/_status}]
```

Works fine if I remove the middleware.

**Comment by CodeMonkeySteve** [comment]
On further investigation, I think the issue is that Rails handles configuring the middleware logger, and that configuration is lost when the middleware is replaced.  You could try copying or recreating the config on the Silencer logger, but I think a better approach is to leave the existing logger middleware and add a silencer middleware before it.  That way the original behavior is preserved, and the silencer middleware can adjust the logging state accordingly.

**Comment by stve** [comment]
Closing as this is quite stale, feel free to re-open.

**Comment by daveharris** [comment]
Hi @stve this is still an issue in rails `v5.2.0` and silencer `v1.0.1`.

As soon as I comment the line 
```
config.middleware.swap Rails::Rack::Logger, Silencer::Logger, silence: ['/healthcheck', /sidekiq/]
```

Then the request ID (in Rails 5 `config.log_tags = [ :uuid ]` was changed to `config.log_tags = [ :request_id ]`) starts showing.

I only stumbled upon this by co-incidence. Only when trying to trace a request through did I notice the request ID wasn't there anymore and kept meaning to find out what change broke it.

Do you have any suggestions? `silencer` is certainly the easiest way to remove things like healthcheck logs, but I really need the request ID in the logs too.

Thanks for the gem, other this it's great, a lifesaver if you are using Amazon Elastic Load Balancer!

**Comment by daveharris** [comment]
Hi @bdehamer,

Yes that works perfectly! Thank you so much! It's really trying to trace requests on a multi-server setup with AJAX requests thrown into the mix!

I'll make a PR to update the Rails documentation in the README ;)
