### ISSUE TITLE
Doesn't work for rails 4.2.6

### ISSUE THREAD

**Issue by floydback** [stve/silencer#18]
In my **production.rb**

```
require 'silencer/logger'
config.middleware.swap Rails::Rack::Logger, Silencer::Logger, :silence => [%r{^/uploads/*}]
```

after reload in production.log

> ActionController::RoutingError (No route matches [GET] "/uploads/123.jpg")

**Comment by stve** [comment]
@floydback what version of the gem were you using? thanks

**Comment by floydback** [comment]
@stve silencer (0.6.0)

**Comment by stve** [comment]
@floydback can I ask that you try the current release candidate `1.0.0.rc3` to see if it works there? I changed a lot from 0.6.0 to 1.x. Thanks

**Comment by metaskills** [comment]
Using Rails 5.0.0.1 I found the latest 1.0.0.rc3 worked for me, however, I had move the config to an initializer or else I would get the following error:

```
...gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/stack.rb:108:in 
`assert_index': No such middleware to insert before: Rails::Rack::Logger (RuntimeError)
```

I only needed this for development. So here is what my `config/initializers/silencer.rb` looks like:

```ruby
Rails.application.configure do
  config.middleware.swap Rails::Rack::Logger, Silencer::Logger, silence: [...]
end if Rails.env.development?
```

Works great! Thanks so much for the gem!

**Comment by albb0920** [comment]
@metaskills I also ran into this, thanks!!

Just in case someone like me also googled that middleware not found error came here.
You can also replace the line 

    config.assets.quiet = true

in your config with

    config.middleware.insert_before Rails::Rack::Logger, Sprockets::Rails::QuietAssets
    config.middleware.swap Rails::Rack::Logger, Silencer::Logger, silence: [...]

to make inserting Sprockets::Rails::QuietAssets run before replacing Rails::Rack::Logger

**Comment by stve** [comment]
Thanks to @metaskills for identifying the initializer as a workaround. I've modified the documentation to make this the recommended approach. Thanks all!
