### ISSUE TITLE
Silence is working for :silence but not for :get

### ISSUE THREAD

**Issue by BrandonShega** [stve/silencer#22]
We have multiple actions on some routes for example /v4/showers/### and I would like to silence the GET methods because we do a lot of polling and it basically just fills up the logs.

I am able to get the silencing to work if I use `:silence => ["/v2/showers", %r{^/v4/showers/\d+}]`

but when I change it to `:get => ["/v2/showers", %r{^/v4/showers/\d+}]`, the logs come back.

Any ideas if I'm doing something wrong?

**Comment by stve** [comment]
hi @BrandonShega sorry you ran into issues. Can you please try the newly minted version `1.0.0`. The method-based configuration was part of the 1.x release. Thanks.

**Comment by stve** [comment]
hi @BrandonShega, hopefully you were able to get past the issue you were having. Feel free to re-open if not.
