### ISSUE TITLE
No such middleware to insert before: Rails::Rack::Logger (RuntimeError)

### ISSUE THREAD

**Issue by snehitgajjar** [stve/silencer#24]
The Same issue persist as mentioned in #21 

rails 5.0.2

**Comment by stve** [comment]
@snehitgajjar can you explain your setup? do you define the middleware in `application.rb`, an initializer, etc.?

**Comment by snehitgajjar** [comment]
Yes so first I had it in `initializers/silencer.rb` it worked fine for `4.2.7.1` and `5.0.2`. But then I moved it to `config/environments/production.rb`. It works with `'rails', '4.2.7.1'` but not with `5.0.2`.

**Comment by stve** [comment]
Configuration in `config/application.rb` or `config/environments/*.rb` is not currently supported. I haven't had a chance to dig too deep, but I suspect that at that point, the middleware stack is not configured (or something). In the meantime, if you are trying to restrict to a specific environment, i'd suggest using `if Rails.env.production?` to conditionally setup the logger.

**Comment by snehitgajjar** [comment]
Thanks @stve it worked.
